# Required to stop the pipeline with an exit code
import sys

# Threshold: maximum allowed error count
MAX_ERRORS = 5
# Patterns that are considered errors
ERROR_PATTERNS = [
    "ERROR",
    "FAILED",
    "Exception",
    "Fatal error",
    "Warning",
]

# Path to the log file generated by the pipeline
LOG_FILE = "build.log"


def analyze_log(log_file):
    """Analyzes the log file for error patterns and returns the count."""
    errors = 0
    found = []

    try:
        with open(log_file, "r") as f:
            for line in f:
                for pattern in ERROR_PATTERNS:
                    if pattern in line:
                        errors += 1
                        found.append(line.strip())
                        break
    except FileNotFoundError:
        print(f"Log file '{log_file}' not found.")
        sys.exit(1)

    return errors, found


def main():
    """Main function: runs the log analysis and exits with appropriate code."""
    print(f"Analyzing log file: {LOG_FILE}")
    print(f"Error threshold: {MAX_ERRORS}")
    print("-" * 40)

    errors, found = analyze_log(LOG_FILE)

    print(f"Errors found: {errors}")

    if found:
        print("\nError lines:")
        for line in found:
            print(f"  {line}")

    print("-" * 40)

    if errors > MAX_ERRORS:
        print(f"FAILED: {errors} errors exceed threshold of {MAX_ERRORS}.")
        sys.exit(1)
    else:
        print(f"PASSED: {errors} errors within threshold of {MAX_ERRORS}.")
        sys.exit(0)


if __name__ == "__main__":
    main()
